### PR TITLE
Provide a way pass cluster provider to run kuberenetes_version.robot tests against custom k8s cluster.

### PR DESCRIPTION
**Pull request by akashshinde**
Signed-off-by: Akash Shinde akshinde@redhat.com

This PR enables running `kubernetes_versions.robot` by providing custom kubernetes-kind information 

### How to run

To run on provided kubernetes cluster. 

Following environment variables are introduced with this PR.
1. `CLUSTER_PROVIDER` (supported values `kind`).
2. `CLUSTER_VERSION` (supported kubernetes versions).
3. `PATH` variable need to have cluster provider scripts path.(`$(pwd)/scripts/cluster_providers`)
 
Then tests should be executed with 
```
robot testsuites/kubernetes_versions.robot
``` 

### Run against multiple kubernetes cluster (comma separated cluster versions)
`export CLUSTER_VERSIONS=1.14.6,1.15.3`
`export CLUSTER_PROVIDER=kind`

Then tests should be executed with 
```
robot testsuites/kubernetes_versions.robot
``` 

#### Run against existing kubernetes cluster created by kind.

Create cluster using

`kind create cluster --image kindest/node:v1.15.3 --name k8s-custom-cluster`

Set env vars
```
export CLUSTER_PROVIDER=kind
export CLUSTER_VERSIONS=1.15.3
export KIND_1_15_3=kind-k8s-custom-cluster
```

Then tests should be executed with 
```
robot testsuites/kubernetes_versions.robot
```

### CODE REVIEW

**Comment by akashshinde** [comment]
@marckhouzam Please review this PR

**Comment by marckhouzam** [comment]
Thank you @akashshinde for this. I haven't had time to look into this yet.

I'll mention this to @jdolitsky who was the one who setup the kind cluster tests.

**Comment by akashshinde** [comment]
@jdolitsky let me know If you've any question.

**Comment by jdolitsky** [comment]
@akashshinde looks good - do you think you can help make this work in the CI tests? At least the one testing k8s version?

```
==============================================================================
Testsuites.Kubernetes Versions :: Verify Helm functionality on multiple Kub...
==============================================================================
Helm works with Kubernetes                                            | FAIL |
Environment variable '%{CLUSTER_VERSIONS}' not found.
------------------------------------------------------------------------------
Testsuites.Kubernetes Versions :: Verify Helm functionality on mul... | FAIL |
1 critical test, 0 passed, 1 failed
1 test total, 0 passed, 1 failed
```

**Review by jdolitsky — CHANGES_REQUESTED** [review]
looks good - plz see comment above

**Comment by akashshinde** [comment]
@jdolitsky sure I'll do it

**Comment by akashshinde** [comment]
@jdolitsky Please check the latest CI run, `Kubernetes_version.robot` test has been passed for k8s v1.15.3. However there are failures in `repos.robot` tests, these tests aren't modified in this PR, Do you think there has been some changes in helm binary itself which is making these fail ?

**Comment by jdolitsky** [comment]
@akashshinde If there are failures unrelated to your PR, I dont see it as reason not to merge.

**Comment by akashshinde** [comment]
@jdolitsky I figured out the issue, pushed fix for that in this same PR (https://github.com/helm/acceptance-testing/pull/86/commits/c3e8470b51f312c4400f9da73d2d8fa1e68c1bd8), I hope that's okay to have the fix in this PR or I can raise another PR. CI should be green now.

**Review by jdolitsky — APPROVED** [review]

**Comment by jdolitsky** [comment]
@akashshinde lgtm. thanks for fixing!

**Pull request merged**
